apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 192.168.1.27:8082/flask-test:latest
        ports:
        - containerPort: 5000
      # This tells K3s to use the credentials we created in Step 1
      imagePullSecrets:
      - name: nexus-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
